namespace: grocery
resources:
  - ../../base
commonLabels:
  app: food-details-integrator-be
configMapGenerator:
  - name: food-details-integrator-be-properties
    literals:
      - PORT=8080
      - GIN_MODE=release
      - REDIS_URL=192.168.86.6:6379
patchesStrategicMerge:
  - deployment_patch.yaml